<a href="https://colab.research.google.com/github/ksandesh2/Python/blob/main/Intro_to_NumPy_for_Data_Computations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


# **Generating Array**


In [3]:
## Generating an identity array
identity_array=np.identity(4)
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#multiplying an array
identity_array*5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [5]:
#Genearating the zero array of a given size
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
#Creating 2-D array: Pass the tuple of rows and columns
#np.zeros((rows, columns))
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
#Creating 2-D array: Pass tuple of rows and columns
#np.ones((rows, columns))
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
#Generate array in a given range
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
#Controling the step size
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
#Alternative linespace for generating the array
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [14]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.linspace(0,20,30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [16]:
#Generating the array with random numbers
#1-D array with 4 random numbers
np.random.rand(4)

array([0.06121149, 0.15403205, 0.21621334, 0.60812357])

In [17]:
#2-D random numbers
np.random.rand(4,5)

array([[0.19761142, 0.88564031, 0.42832435, 0.56321692, 0.64565206],
       [0.88016743, 0.84791817, 0.7069104 , 0.50361965, 0.08405222],
       [0.27571382, 0.33528552, 0.34798015, 0.68531747, 0.7171007 ],
       [0.94235827, 0.13898299, 0.44674336, 0.59706099, 0.23771826]])

In [18]:
#Generate 10 random integers in a given range
np.random.randint(5,50,10)

array([27, 18, 27, 21, 23, 49, 11, 44, 45,  5])

** 2D Array Indexing and** **Selection**


```
** Array Indexing and Selection**
```



In [22]:
#Creating 1-D vector
arrray_1d=np.array([1,2,3,4,5])

In [23]:
#Slicing an 1-D array
arrray_1d[-1]

5

In [19]:
#indexing 2D array
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
#Selecting the individual element
##array_2d[row][column]
##Let's select 5, that is row 1, column 1( we start from 0)
array_2d[1][1]

5

In [20]:
#Select 9
array_2d[2][2]

9

In [21]:
#Selecting whole row
#array_2d[row]
array_2d[1]

array([4, 5, 6])

In [24]:
#Selecting conditionally rows and columns
array_2d[:2,:]
# :2 denotes we are selecting the rows upto 2
# : denotes we are selecting all the columns

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#Selecting first two rows and first two columns
array_2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
array_2d[:2,0:2]

array([[1, 2],
       [4, 5]])

In [30]:
#return second row
array_2d[1,:]

array([4, 5, 6])

In [33]:
array_2d[:,2]

array([3, 6, 9])

In [34]:
array_2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [37]:
array_2d[:,0]

array([1, 4, 7])

**Conditional Selection**

In [38]:
arr=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [41]:
#Selecting elements that are less than 6
arr[arr <6 ]

array([1, 2, 3, 4, 5])

In [42]:
# >6
arr[arr>6]

array([7, 8, 9])

In [44]:
# All even numbers
arr[arr %2==0]

array([2, 4, 6, 8])

In [45]:
#All odd numbers in array
arr[arr %2!=0]

array([1, 3, 5, 7, 9])

In [46]:
##Multiple conditions, in all odd numbers having return value greater or equal to 5
arr[(arr %2 !=0) & (arr>=5)]

array([5, 7, 9])

In [47]:
#Using logical selection
arr>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [48]:
## checking for 0
arr ==0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

Basic Array Operations
Additions, Subtraction, Multiplication, Divison, Squaring


In [49]:
#Create two arrays
arr1=np.arange(0,5)
arr2=np.arange(6,11)

In [50]:
arr1 +arr2

array([ 6,  8, 10, 12, 14])

In [51]:
#subtraction
arr2-arr1

array([6, 6, 6, 6, 6])

In [52]:
#Multiplication
arr1*arr2

array([ 0,  7, 16, 27, 40])

In [53]:
#Division
arr1/arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [54]:
#Calculating the sin of arr1
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [56]:
#Creating cosine of arr1
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [57]:
#calculating the tangent(tan) of array
np.tan(arr1)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [58]:
#Calculating the logarithm of arr2
np.log(arr2)

array([1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [60]:
#Exponential values
np.exp(arr2)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [61]:
#Calculating the power of the array

## 0^6=0, 1^7=1, 2^8=256..
np.power(arr1, arr2)

array([      0,       1,     256,   19683, 1048576])

In [62]:
#Comparison of array
np.greater(arr1, arr2)

array([False, False, False, False, False])

# **Basic statistics**

In [66]:

arr=np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

Standard deviation

In [68]:
#Standard deviation of array
np.std(arr)

1.4142135623730951

In [71]:
arr2=np.array([[3,4],[5,6]])
np.std(arr2)

1.118033988749895

In [72]:
#Specifying the axis
##By default the std is computed on the flattened values or converted into single values
np.std(arr2, axis=0)

array([1., 1.])

In [73]:
np.std(arr2, axis=1)

array([0.5, 0.5])

# **Variance**

In [75]:
arr=np.arange(0,10)
np.var(arr)

8.25

In [76]:
np.var(arr2)

1.25

In [78]:
#Mean
np.mean(arr)

4.5

In [79]:
np.average(arr)

4.5

Median

In [80]:
np.median(arr)

4.5

**Minimum and Maximum**

In [81]:
np.min(arr)

0

In [82]:
np.max(arr)

9

**Data manipulation**

In [85]:
arr1=np.arange(0,10)
arr2=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [86]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.shape(arr1)

(10,)

In [89]:
np.shape(arr2)

(3, 3)

Shaping the **Array**

In [ ]:
#np.reshape(array_name, newshape=(rows, columns) or array_name.reshape(rows, columns) change the shape of the array. The rows and columns of the new shape has to comform with the existing data of the array.

In [90]:
np.reshape(arr1, newshape=(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [91]:
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
arr2_reshape=arr2.reshape(9,1)
arr2_reshape

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])